### ISSUE TITLE
适配不是很好

### ISSUE THREAD

**Issue by lovestart** [HotBitmapGG/CreditSesameRingView#2]
看了你的这个项目，觉得真心不错，学到了很多东西。项目有的问题就是适配不是很好，在小手机整个布局乱套了，相比支付宝的信用控件在小手机整体缩小（我是在3.5寸的手机上遇到的）
![image](https://cloud.githubusercontent.com/assets/8360241/18384008/cacafb14-76ba-11e6-9bb6-76c5f8a00f87.png)

**Comment by HotBitmapGG** [comment]
3.5的屏幕这个真的是没有考虑到啊， @lovestart
